name: Generate Terraform Docs

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base repo (safe)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.WRITE_PAT }}

      - name: Generate terraform docs (from base only)
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          output-file: README.md
          output-method: replace
          git-push: "true"
